language: java
sudo: required
services:
- docker
jdk: oraclejdk8
install: gradle assemble
script: gradle check

after_success:
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - export REPO=arne2/fapcrawler
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker build -f dockerfile -t $REPO:$COMMIT .
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
  - if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then docker push $REPO ; fi

notifications:
  email: false
env:
  global:
  - secure: nJGqiDfrI+mxEd3dXF3+35fLAKMuPYqCwJSWEtRQjKDZFch56Sbgq99pFvHDxQw5thxAje0uMkcDgJiulr2fjEMLoir0TuKmu3nrF4LQDswMBDb7PMSxn+tTqdXbAj+pySb/ENVVoKRdjo33EZoqao3wWFmMUALk9leL0S249JfpD1aMD/XHHfjb9QA8ZD6UL47l5j7hFadNjBM5xMVoFZ52O09bs79swel4sPcTasKIML2TcCJDi3G94snKM44GprnzKHc0gNyqN7cpkM5zXZb8abC/iA8ePnohMpnRcC+kAI47snxX82TPGR4tDqCroV4CprfyEpKlkY39I4I1U8T81h0OtpYySINIUVfJCjLyNO5DJbPdMYXHrat/Vs++g2KPdWT7iYio4r67AfbqqnDrSmiYfMrb2tOyMWUf5LGUvtrwAOHME3KmJeJFwjbwehIzWUq3xxi5ejWhKDZ+v92HFMB9ih0AikD/yXglr4nCcQ4vbowiwAUXiZxtq5rKbDt3pU0xu6cBxurPo9POVGXcndORzpSKpUHxpKW6s947cgxub5Tjzizy/V7HyaOy17zdNXM/o7bWRVzHYddN2cCXYEcsZO6lh7250PKOYp8e+VL7I9qk1iYBWXNGPv6jlbaCnlWhsewPIfwJRlgSVROxAoLWGjn6IoWM/dUTb0E=
  - secure: Pnypzr8Yarf+dl5SoFWdHiz8/sI7vkb17YK7unnManSf2HKP3shXy8GK/03rQhcwAM/G2F+ACo3lV8FMwyDfAjp6HEsOGZDAyhM5KeLSiEd0Jc4QqgG+1CzI42852EdRnN7Yx/6eCPedfNI0jYh7ldyuAUan3851utSdjJy1o5vEsvLfhi/Xwbrzu0fKeGz2kaoLQh8VD46vR0Rp+IMrwz9Pw2S5NEdK9H5IQMXTCY08wfEwCyLyKcB8snzp5iYiq5uM8uhIqzosLnPXrM43TSOgwafsrgJvwXwNxbQM5Qurevt4U5ZCvVEpdY4tW8eCbvj2c3N46n9pJhGtJEVYl3thqEa3nAo+l7EoiXuW/0oTNFM+dUX9W0i5D/Q95NJ7ORcTOphuxGytyjCbDs3LQHNHgAc1/jte8y9xE3NV63mj+Y/dz9rgecSJueRBCwgY3jCpNId8nlSiWDHT/w0xOzvUQ95Xrh5annCl7TXiOF2zqpvVGtBO+oaMNxg5wCppBZNrSE1A1Zva0QznVN2P4IzVGof6FXj8BaoYNEfD3zQ0Q79vnEh7J9mTNZSizK4Kq/AI/XeRuOUmA+qexN5Kb9DaLmhFPe1yj3mjsDHQlQfuLiURY8U4kPh3goySy1NHWZpyB47AdrtT6MbxS+6GiRzpK5LE+HxdUwXczFrxloY=
  - secure: sE/K/eZ9hoNtBfsoeqA/gdPxUGRuWzkrH231oqZiYtI4LsKSypxMvCnv9lXWStikOFWsoC31IoC7EpS9CF390xvTvwGE8wuVxkZnZerHaGXm2glel//5zb+XrHCd7AFSd+Bc/aVYI1ayMm7LSyOzny4wYIqPYJC4U/vav29tvUvddaYcNMZKymlrYQU9H/KnG64ukjIF+3bMPqrZjoveTyfekUgl+P1ZRxNfrnMjIFV7dS010SFQD00iLBmo9w5KfKizUAdlEgbWuN1BeROOAKz+NBGaAZ50dHmMn8cmioTZgOanMHSQeruWNzU/aYM044TDvxbRw+eDjvysT6fQJT7eVvq5Tnc8HlSds1wWOzTpjv1ow4skfOjKICmPB8wn5H3kuvbc6hvr1sYOIeHgSzvQ/ceRQvNPlnAkGx8PWn2zvI2+rl6Af3zA6694lhecICF1xmReKh3v6y8ah5DIalDQPrF9rby3Cb/6bi/GrohzH2+Dtjyd9rRawv28IeScTiXvF+wpnQBbV8N2JdDLNTabi571OmnQAtODfspB0ElnVt+w5KNw4+oYA+dUNhMuwRsHY6xCJBiYMJ2tlwOzVEn3fiEvPxCyFU8/+O8UYcg7PO13YrfGg/TKH08cjf8t//U0WZpXNF/tZpNojXz/TfOb7kuL5sIfd1GqiEGvLxE=
