language: java
sudo: required
services:
- docker
jdk: oraclejdk8
install: gradle assemble
script: gradle check

after_success:
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - export REPO=arne2/fapcrawler
  - export TAG=`then echo "latest"; else echo $TRAVIS_BRANCH ;`
  - docker build -f dockerfile -t $REPO:$COMMIT .
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then docker push $REPO ; fi

notifications:
  email: false
env:
  global:
  - secure: fARomsq5fkRRd4QGBr7kus2V7XuFLLQAZTD4eKXvFjaCAmH0tVa7QEYuqsSgHOJr4FJGoNukUkA8Sqz6G/s4W//MGAWgocmjBioSXz/hfN34HaBr2XTWisPhSiKwJB+jCmXyfBTpWYuKGslt+Nq9ydVBu3YvnIcLEbknLiHyjQQ=
  - secure: Xejkp5cHxvy7btVAiVMBDeV0NRirVy7bDMHqJXL06nIGTnYPPTXpTZa0ED96vChPb/PTUx23QkwoIM1suhecY1+/f+KVGjBWnnh6f6ZRI6lz2e51Zf1ZApV3WqCaB6HcnpUkrmbDmWI68RUmLlYZp12mTSKVHdyJ9gnOUZvNnu8=
  - secure: jdtCHC/nyqMeee1dEv2mezfUPhmS/uomoRQgF9FwC7a7TkaLT04mTCQ/6b35BQt7iEaL+gmhioEX+UNutKjzsQnb8EQN1MQ71rM6ke01XdfpwgWEW79eHCf1499f3w/D/nb5DwG03mW7nEnU9naF6JI7aEe9wWuHoDWPs8yql2c=



